import { NextResponse } from 'next/server';
import { buildWebsitePrompt } from '@/lib/ai';

export async function POST(req: Request) {
  const body = await req.json();
  const prompt = buildWebsitePrompt(body.message || 'Create a hero section');

  return NextResponse.json({
    reply: `Generated website draft for: ${prompt}`,
    html: '<section><h1>Generated by AI</h1><p>Edit me inline.</p></section>',
    css: 'section{padding:2rem;font-family:Inter,sans-serif;}h1{font-size:2rem;}'
  });
}
